name: ci

on:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get GIT Tag
        if: startsWith(github.ref, 'refs/tags/')
        id: git_tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - uses: haya14busa/action-cond@v1
        id: docker_tag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ steps.git_tag.outputs.tag }}
          if_false: 'latest'
      - uses: marceloprado/has-changed-path@v1
        id: has_changed_path
        with:
          paths: Dockerfile
      - name: Build and push
        if: steps.has_changed_path.outputs.changed == 'true'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}:${{ steps.docker_tag.outputs.value }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
